import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 10.0

[font.bold]
family = "3270 Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "3270 Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "3270 Nerd Font Mono"
style = "Italic"

[font.normal]
family = "3270 Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
{ key = "Return", mods = "Alt", action = "ToggleFullScreen" },
{ key = "1", mods = "Alt", chars = "cd /home/Radmil/Desktop/podsite-web/app/\nsource backend-venv/bin/activate\nnvim\n" },
{ key = "2", mods = "Alt", chars = "cd /home/Radmil/Desktop/podsite-web/app/\nsource backend-venv/bin/activate\ncd backend\npython manage.py runserver\n"},
{ key = "3", mods = "Alt", chars = "cd /home/Radmil/Desktop/podsite-web/app/\ncd frontend\nnpm run dev\n"},
{ key = "4", mods = "Alt", chars = "cd /home/Radmil/Desktop/podsite-web/app/\nsource backend-venv/bin/activate\ncd rsnet\n" },
{ key = "9", mods = "Alt", chars = "setxkbmap -layout us\n"},
{ key = "8", mods = "Alt", chars = "setxkbmap -layout cz -variant qwerty\n"},]

[window]
opacity = 1
